### ISSUE TITLE
Improve Frontend Document Comments

### ISSUE THREAD

**Issue by Nate-Louder** [EECE3093C/team-project-golden-girls#40] opened 2023-03-04 01:34 UTC

**Comment by jimmygerman99** [comment] 2023-03-21 19:32
Duplicate of issue #41
No reason for this issue to be here

**Comment by jimmygerman99** [comment] 2023-03-21 19:33
Duplicate of issue #41
No reason for us to have two of the same issue

**Closed by jimmygerman99** 2023-03-21 19:33 UTC
Labels: documentation
